### ISSUE TITLE
Really Important Issue

### ISSUE THREAD

**Issue by Jefff000** [H4xton/Website-Crasher#1]
I tried this on the websites:
Google.com, Facebook.com, Apple.com, Discord.com AND Spotify.com

To my surprise, it didn't work!1!
Could you please update the script.

**Comment by H4xton** [comment]
> 
> 
> I tried this on the websites:
> Google.com, Facebook.com, Apple.com, Discord.com AND Spotify.com
> 
> To my surprise, it didn't work!1!
> Could you please update the script.

Needs to be executet throu a Payload Also stop playing dumbass

**Comment by Jefff000** [comment]
What in all hell?!!

This is extremely unproffesional.
